root = "."
tmp_dir = "dist"

[build]
cmd = "make build"
bin = "dist/kuki"
full_bin = "./dist/kuki"
include_ext = ["go", "tpl", "tmpl", "json", "sql", "yaml"]
exclude_dir = ["tmp", "vendor", "build"]
include_dir = []
exclude_file = []
log = "dist/app.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true