version: '3,8'
services:
  db-kuki:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: kuki
      POSTGRES_PASSWORD: kuki
      POSTGRES_DB: kuki
    ports:
      - 5432:5432
    volumes:
      - db-kuki:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
volumes:
  db-kuki:
    name: db-kuki
