version: '3,8'
services:
  kuki:
    image: kuki:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1323:1323
      - 50051:50051
    depends_on:
      - db-kuki
      - jaeger
    volumes:
      - kuki:/app
    environment:
      - GRPC_PORT=50051
      - REST_PORT=1323
      - DB_HOST=db-kuki
      - DB_PORT=5432
      - DB_USER=kuki
      - DB_PASS=kuki
      - DB_NAME=todos
      - DB_SSL=disable
    restart: on-failure
    networks:
      - kuki

  db-kuki:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: kuki
      POSTGRES_PASSWORD: kuki
      POSTGRES_DB: kuki
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - db-kuki:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - kuki

  jaeger:
    container_name: jaeger_container
    restart: always
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - kuki

  grafana:
    container_name: grafana_container
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - kuki
    depends_on:
      - jaeger
    volumes:
      - ./provisioning:/etc/grafana/provisioning

volumes:
  db-kuki:
    name: db-kuki
  kuki:
    name: kuki

networks:
  kuki:
    driver: bridge
